# Generated by Django 3.2.9 on 2021-11-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('I', 'Idle'), ('R', 'Running'), ('Q', 'Queued'), ('S', 'Success'), ('F', 'Failed'), ('C', 'Canceled')], default='I', max_length=1),
        ),
    ]
